### ISSUE TITLE
Log error

### ISSUE THREAD

**Issue by maiorca85** [gfjardim/service.subtitles.legendastv#17]
Tenho este erro ja a algum tempo. Esta tudo actualizado. Pode me ajudar?

**Comment by gfjardim** [comment]
Qual seria o erro? Me manda um debug log.

**Comment by maiorca85** [comment]
Ja esta a funcionar. Acho que era mesmo um problema com o meu log no
website.  Tive de me logar no website e resolveu. Pelos vistos nao era
problema do add-on. Obrigado pelo optimo trabalho.

**Comment by lrrosa** [comment]
A algumas semanas começou a aparecer esse mesmo bug aqui e não faz o download da legenda.
Sistema: Librelec 7.0.3 (generic.x86_64) / Kodi 16.1 / Python 2.7.11

Segue o log:

> 19:11:19 T:139631249053440   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.UnicodeDecodeError'>
                                            Error Contents: 'ascii' codec can't decode byte 0xc3 in position 110: ordinal not in range(128)
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/service.subtitles.legendastv/service.py", line 321, in <module>
                                                subs = Download(params["download_url"],'filename', pack, params['lang'])
                                              File "/storage/.kodi/addons/service.subtitles.legendastv/service.py", line 170, in Download
                                                extract_and_copy()
                                              File "/storage/.kodi/addons/service.subtitles.legendastv/service.py", line 137, in extract_and_copy
                                                log("Opening file: "+dirfile, "DEBUG")
                                              File "/storage/.kodi/addons/service.subtitles.legendastv/resources/lib/LTVutilities.py", line 37, in log
                                                xbmc.log((u"### [%s] - %s" % (__scriptname__,msg,)).encode('utf-8'), level=loglevel )
                                            UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 110: ordinal not in range(128)
                                            -->End of Python script error report<--
19:11:19 T:139631525881600   ERROR: GetDirectory - Error getting plugin://service.subtitles.legendastv/?action=download&download_url=http://legendas.tv/download/58979301ae10a/Colony/Colony_S02E04_HDTV_x264_FLEET_AFG_Mobile_mSD_AVS_MeGusta_CRAVERS_RARBG_LiGaS_KiNGS&filename=Colony - S02E04 - Panopticon.mkv&pack=false&lang=Portuguese (Brazil)
