### ISSUE TITLE
Exception when selecting subtitle for download

### ISSUE THREAD

**Issue by beothorn** [gfjardim/service.subtitles.legendastv#22]
23:25:53.337 T:1514218416   DEBUG: ### [Legendas.TV] - Version: 2.3.2
23:25:53.338 T:1514218416   DEBUG: ### [Legendas.TV] - Action 'download' called
23:25:54.210 T:1514218416   DEBUG: ### [Legendas.TV] - Opening URL: (http://legendas.tv/download/59da3043538f7/The_Dark_Tower/The_Dark_Tower_2017_1080p_BluRay_x264_DTS_SHITBOX)
23:25:55.872 T:1832903600   DEBUG: Previous line repeats 1 times.
23:25:55.872 T:1832903600   DEBUG: Failed to connect to LIRC. Giving up.
23:25:55.872 T:1832903600   DEBUG: Thread RemoteControl 1832903600 terminating
23:25:56.392 T:1514218416   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.TypeError'>
                                            Error Contents: must be string or buffer, not None
                                            Traceback (most recent call last):
                                              File "/root/.kodi/addons/service.subtitles.legendastv/service.py", line 321, in <module>
                                                subs = Download(params["download_url"],'filename', pack, params['lang'])
                                              File "/root/.kodi/addons/service.subtitles.legendastv/service.py", line 122, in Download
                                                with open(fname,'wb') as f: f.write(FileContent)
                                            TypeError: must be string or buffer, not None
                                            -->End of Python script error report<--
23:25:56.393 T:1945731744   DEBUG: ------ Window Init (DialogNotification.xml) ------

**Comment by BillVGN** [comment]
Same issue with me. Log contents with same exception messages on "service.py" file.
Please, verify.
